version: '3.4'

services:
    
  cachedb:
    image: redis:alpine

  blogdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  blog.api:
    image: ${DOCKER_REGISTRY-}blogapi
    build:
      context: .
      dockerfile: Blog.API/Dockerfile

  cache.api:
    image: ${DOCKER_REGISTRY-}cacheapi
    build:
      context: .
      dockerfile: Cache.API/Dockerfile

  blog.web:
    image: ${DOCKER_REGISTRY-}blogweb
    build:
      context: .
      dockerfile: Blog.Web/Dockerfile

