version: '3.4'

services:
    
  cachedb:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  blog.api:
    image: ${DOCKER_REGISTRY-}blogapi
    build:
      context: .
      dockerfile: Blog.API/Dockerfile
